Adds logic for Root CA renewal
canonical/self-signed-certificates-operator pull request #15
Opened 2023-07-05 11:53 UTC by saltiyazan

# Description

Handles the expiration of the Juju secret that stores the Root CA, and generates a new one when expired.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2023-07-05 13:07 UTC, ghislainbourgeois requested changes

2023-07-05 13:07 UTC, ghislainbourgeois commented on src/charm.py
> +            event: Union[ConfigChangedEvent, SecretExpiredEvent]
```suggestion
            event: EventBase
```

2023-07-06 07:04 UTC, saltiyazan commented on src/charm.py
> +            event: Union[ConfigChangedEvent, SecretExpiredEvent]
Done.

2023-07-07 13:10 UTC, ghislainbourgeois approved these changes

2023-07-10 10:02 UTC, merged